import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import {
  SidebarProvider,
  SidebarTrigger,
} from "@/components/animate-ui/radix/sidebar";
import { AppSidebar } from "@/app/(routes)/(root)/components/AppSidebar/AppSidebar";
import { Navbar } from "@/components/Shared/Navbar/Navbar";
import { SyncUserClient } from "@/components/syncUserClient";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="es" className={`${roboto.className}   `}>
        <body className="antialiased font-roboto">
          <SidebarProvider>
            <AppSidebar />
            <div className="w-full bg-[#F3F5F4] flex flex-col min-h-screen">
              <Navbar />
              <main>{children}</main>
            </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
